import { MetadataRoute } from "next";
import { SPAM_DISALLOWS } from "./spam_disallow";

const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://golf2go.co.nz";

const allow = [
  "/",
  "/about",
  "/courses",
  "/gallery",
  "/book",
  "/terms",
  "/help",
  "/privacy",
  "/favicon.ico",
  "/manifest.json",
  "/sitemap.xml",
];

const coreDisallow = [
  "/api/",
  "/_next/",
  "/static/",
  "/*.php$",
  "/*.html$",
  "/*.asp$",
  "/*.aspx$",
  "/*.jsp$",
  "/*.cgi$",
  "/*.pl$",
  "/*.sql$",
  "/*.zip$",
  "/*.tar$",
  "/*.gz$",
  "/*.log$",
  "/*.bak$",
  "/*.json$",
  "/*.exe$",
  "/*.dll$",
  "/*.jar$",
  "/wp-*",
  "/wordpress/",
  "/dup-installer/",
  "/xmlrpc.php",
  "/install/",
  "/admin/",
  "/login/",
  "/backup/",
  "/cache/",
  "/feed/",
  "/rss/",
  "/.well-known/",
  "/.env",
  "/.git/",
  "/.svn/",
  "/.htaccess",
  "/.htpasswd",
  "/cgi-bin/",
  "/bin/",
  "/temp/",
  "/tmp/",
  "/assets/admin/",
  "/includes/",
  "/misc/",
  "/modules/",
  "/profiles/",
  "/scripts/",
  "/updates/",
  "/upgrade/",
  "/vendor/",
  "/*/[0-9]*u[0-9]*",
  "/[a-z]{2,6}/[0-9]+u[0-9]+",
  "/[a-z]{3,8}/*",
  "/a2f6product/*",
  "/*-[0-9][0-9][0-9][0-9][0-9][0-9].html$",
  "/*-[0-9][0-9][0-9][0-9][0-9].html$",
  "/product/*",
  "/reviews/*",
  "/20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]/*",
  "/tag/*",
  "/Fix-*",
  "/NEW-*",
  "/*/reviews",
  "/product_id/*",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow,
        disallow: [...coreDisallow, ...SPAM_DISALLOWS],
        crawlDelay: 10,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
